// tests/notebook-offline-replay.test.ts
//
// A NOTEBOOK EDIT MADE OFFLINE LANDS EXACTLY ONCE ON RECONNECT. The queue
// replays ops verbatim, so the proof is at the op layer: applyNotebookOp (the
// exact function the WriteQueue delegates notebook ops to) is driven twice
// with the same client-minted id against the real stack, and exactly one row
// exists. The negative control replays the same payload under a DIFFERENT id
// and gets a second row, which is what shows the dedup comes from the id and
// not from the values. Recap edits (summary, confirm) replay idempotently on
// the row the server generated.

import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import {
	applyNotebookOp,
	notebookDelete,
	notebookInsert,
	notebookUpdate,
	recapUpdate
} from '$lib/notebook/ops';
import {
	cleanupRun,
	closeDb,
	createStudent,
	createTeam,
	seedMentor,
	serviceClient,
	signIn,
	type Client,
	type SeededMentor,
	type SeededStudent,
	type SeededTeam
} from './db/harness';

let mentor: SeededMentor;
let team: SeededTeam;
let rita: SeededStudent; // notebook_values_lead
let theo: SeededStudent; // no role
let ritaClient: Client;
let theoClient: Client;

const service = serviceClient();

let recapId: string;

beforeAll(async () => {
	mentor = await seedMentor('nbreplay');
	team = await createTeam(mentor.client, 'NB Replay');
	rita = await createStudent(mentor.client, team, 'Rita', 'R');
	theo = await createStudent(mentor.client, team, 'Theo', 'T');
	const { error } = await mentor.client.rpc('role_assign', {
		p_team_id: team.teamId,
		p_student_id: rita.studentId,
		p_role: 'notebook_values_lead',
		p_tier: 'primary'
	});
	if (error) throw new Error(`role_assign failed: ${error.message}`);
	ritaClient = await signIn(rita.email, rita.pin);
	theoClient = await signIn(theo.email, theo.pin);

	// A real session, so a recap row exists the way it does in production:
	// generated by the server at meeting end, never inserted by a client.
	const created = await mentor.client.rpc('meeting_create', {
		p_kind: 'friday',
		p_meeting_date: new Date().toISOString().slice(0, 10),
		p_planned_start_at: new Date().toISOString()
	});
	if (created.error) throw new Error(`meeting_create failed: ${created.error.message}`);
	const meetingId = (created.data as { meeting_id: string }).meeting_id;
	await mentor.client.rpc('meeting_start', { p_meeting_id: meetingId });
	await mentor.client.rpc('meeting_end', { p_meeting_id: meetingId });
	const { data: recap } = await service
		.from('meeting_recaps')
		.select('id')
		.eq('meeting_id', meetingId)
		.eq('team_id', team.teamId)
		.single();
	recapId = recap!.id;
});

afterAll(async () => {
	await cleanupRun();
	await closeDb();
});

describe('replayed entries', () => {
	const entryId = crypto.randomUUID();
	const row = () => ({
		id: entryId,
		team_id: team.teamId,
		section: 'core_values' as const,
		prompt_key: 'cv-stuck',
		body: 'We asked the Blue Team for the gyro trick.',
		authored_by_student_id: rita.studentId
	});

	test('the same op twice is one row: the second landing is a duplicate key, which counts as done', async () => {
		expect(await applyNotebookOp(ritaClient, notebookInsert(row()))).toBe('done');
		// The reconnect replay: the op is applied again, verbatim.
		expect(await applyNotebookOp(ritaClient, notebookInsert(row()))).toBe('done');

		const { data } = await service.from('notebook_entries').select('id').eq('id', entryId);
		expect(data).toHaveLength(1);
	});

	test('NEGATIVE CONTROL: the same payload under a different id is a second row', async () => {
		const otherId = crypto.randomUUID();
		expect(await applyNotebookOp(ritaClient, notebookInsert({ ...row(), id: otherId }))).toBe('done');

		const { data } = await service
			.from('notebook_entries')
			.select('id')
			.eq('team_id', team.teamId)
			.eq('body', 'We asked the Blue Team for the gyro trick.');
		expect(data).toHaveLength(2);

		await service.from('notebook_entries').delete().eq('id', otherId);
	});

	test('replayed updates are last-write-wins and idempotent', async () => {
		const op = notebookUpdate(entryId, { body: 'The gyro trick fixed our turns.' });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const { data } = await service.from('notebook_entries').select('body').eq('id', entryId);
		expect(data).toEqual([{ body: 'The gyro trick fixed our turns.' }]);
	});

	test('a refused update is SHOWN, not swallowed: zero rows plus a visible row is a refusal', async () => {
		const res = await applyNotebookOp(theoClient, notebookUpdate(entryId, { body: 'overwritten' }));
		expect(res).toEqual({ message: 'The server did not accept this change.' });

		const { data } = await service.from('notebook_entries').select('body').eq('id', entryId);
		expect(data).toEqual([{ body: 'The gyro trick fixed our turns.' }]);
	});

	test('a replayed delete is done both times, and an edit whose target is gone is done, not an error', async () => {
		expect(await applyNotebookOp(ritaClient, notebookDelete(entryId))).toBe('done');
		expect(await applyNotebookOp(ritaClient, notebookDelete(entryId))).toBe('done');

		const { data } = await service.from('notebook_entries').select('id').eq('id', entryId);
		expect(data).toHaveLength(0);

		expect(await applyNotebookOp(ritaClient, notebookUpdate(entryId, { body: 'ghost' }))).toBe('done');
	});
});

describe('replayed recap edits', () => {
	test('the summary is last-write-wins and idempotent on the server-generated row', async () => {
		const op = recapUpdate(recapId, { summary: 'We planned the season kickoff.' });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const { data } = await service.from('meeting_recaps').select('summary').eq('id', recapId);
		expect(data).toEqual([{ summary: 'We planned the season kickoff.' }]);
	});

	test('a replayed confirm stamps once and stays stamped', async () => {
		const op = recapUpdate(recapId, { confirmed: true });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const first = await service
			.from('meeting_recaps')
			.select('confirmed_at, confirmed_by_student_id')
			.eq('id', recapId)
			.single();
		expect(first.data?.confirmed_at).not.toBeNull();
		expect(first.data?.confirmed_by_student_id).toBe(rita.studentId);

		// The replay: still confirmed, and the ORIGINAL stamp stands.
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		const second = await service
			.from('meeting_recaps')
			.select('confirmed_at, confirmed_by_student_id')
			.eq('id', recapId)
			.single();
		expect(second.data?.confirmed_at).toBe(first.data?.confirmed_at);
		expect(second.data?.confirmed_by_student_id).toBe(rita.studentId);
	});

	test('a teammate without the role is refused, visibly', async () => {
		const res = await applyNotebookOp(theoClient, recapUpdate(recapId, { summary: 'not mine' }));
		expect(res).toEqual({ message: 'The server did not accept this change.' });

		const { data } = await service.from('meeting_recaps').select('summary').eq('id', recapId);
		expect(data).toEqual([{ summary: 'We planned the season kickoff.' }]);
	});
});
