// tests/notebook-offline-replay.test.ts
//
// A NOTEBOOK EDIT MADE OFFLINE LANDS EXACTLY ONCE ON RECONNECT. The queue
// replays ops verbatim, so the proof is at the op layer: applyNotebookOp (the
// exact function the WriteQueue delegates notebook ops to) is driven twice
// with the same client-minted id against the real stack, and exactly one row
// exists. The negative control replays the same payload under a DIFFERENT id
// and gets a second row, which is what shows the dedup comes from the id and
// not from the values. Recap edits (summary, confirm) replay idempotently on
// the row the server generated.

import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import {
	applyNotebookOp,
	notebookDelete,
	notebookRestore,
	notebookInsert,
	notebookUpdate,
	recapUpdate
} from '$lib/notebook/ops';
import {
	cleanupRun,
	closeDb,
	createStudent,
	createTeam,
	seedMentor,
	serviceClient,
	signIn,
	type Client,
	type SeededMentor,
	type SeededStudent,
	type SeededTeam
} from './db/harness';

let mentor: SeededMentor;
let team: SeededTeam;
let rita: SeededStudent; // notebook_values_lead
let theo: SeededStudent; // same team, no role: writes everything since 0026
let rival: SeededTeam;
let zia: SeededStudent; // ANOTHER team: the refusal this file still needs
let ritaClient: Client;
let theoClient: Client;
let ziaClient: Client;

const service = serviceClient();

let recapId: string;

beforeAll(async () => {
	mentor = await seedMentor('nbreplay');
	team = await createTeam(mentor.client, 'NB Replay');
	rita = await createStudent(mentor.client, team, 'Rita', 'R');
	theo = await createStudent(mentor.client, team, 'Theo', 'T');
	rival = await createTeam(mentor.client, 'NB Replay Rival');
	zia = await createStudent(mentor.client, rival, 'Zia', 'Z');
	const { error } = await mentor.client.rpc('role_assign', {
		p_team_id: team.teamId,
		p_student_id: rita.studentId,
		p_role: 'notebook_values_lead',
		p_tier: 'primary'
	});
	if (error) throw new Error(`role_assign failed: ${error.message}`);
	ritaClient = await signIn(rita.email, rita.pin);
	theoClient = await signIn(theo.email, theo.pin);
	ziaClient = await signIn(zia.email, zia.pin);

	// A real session, so a recap row exists the way it does in production:
	// generated by the server at meeting end, never inserted by a client.
	const created = await mentor.client.rpc('meeting_create', {
		p_kind: 'friday',
		p_meeting_date: new Date().toISOString().slice(0, 10),
		p_planned_start_at: new Date().toISOString()
	});
	if (created.error) throw new Error(`meeting_create failed: ${created.error.message}`);
	const meetingId = (created.data as { meeting_id: string }).meeting_id;
	await mentor.client.rpc('meeting_start', { p_meeting_id: meetingId });
	await mentor.client.rpc('meeting_end', { p_meeting_id: meetingId });
	const { data: recap } = await service
		.from('meeting_recaps')
		.select('id')
		.eq('meeting_id', meetingId)
		.eq('team_id', team.teamId)
		.single();
	recapId = recap!.id;
});

afterAll(async () => {
	await cleanupRun();
	await closeDb();
});

describe('replayed entries', () => {
	const entryId = crypto.randomUUID();
	const row = () => ({
		id: entryId,
		team_id: team.teamId,
		section: 'core_values' as const,
		prompt_key: 'cv-stuck',
		body: 'We asked the Blue Team for the gyro trick.',
		authored_by_student_id: rita.studentId
	});

	test('the same op twice is one row: the second landing is a duplicate key, which counts as done', async () => {
		expect(await applyNotebookOp(ritaClient, notebookInsert(row()))).toBe('done');
		// The reconnect replay: the op is applied again, verbatim.
		expect(await applyNotebookOp(ritaClient, notebookInsert(row()))).toBe('done');

		const { data } = await service.from('notebook_entries').select('id').eq('id', entryId);
		expect(data).toHaveLength(1);
	});

	test('NEGATIVE CONTROL: the same payload under a different id is a second row', async () => {
		const otherId = crypto.randomUUID();
		expect(await applyNotebookOp(ritaClient, notebookInsert({ ...row(), id: otherId }))).toBe('done');

		const { data } = await service
			.from('notebook_entries')
			.select('id')
			.eq('team_id', team.teamId)
			.eq('body', 'We asked the Blue Team for the gyro trick.');
		expect(data).toHaveLength(2);

		await service.from('notebook_entries').delete().eq('id', otherId);
	});

	test('replayed updates are last-write-wins and idempotent', async () => {
		const op = notebookUpdate(entryId, { body: 'The gyro trick fixed our turns.' });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const { data } = await service.from('notebook_entries').select('body').eq('id', entryId);
		expect(data).toEqual([{ body: 'The gyro trick fixed our turns.' }]);
	});

	test('a teammate with no role edits through the same op path (0026)', async () => {
		const res = await applyNotebookOp(theoClient, notebookUpdate(entryId, { body: 'Theo fixed the wording.' }));
		expect(res).toBe('done');

		const { data } = await service.from('notebook_entries').select('body').eq('id', entryId);
		expect(data).toEqual([{ body: 'Theo fixed the wording.' }]);

		// Put it back, so the ops below read the sentence they expect.
		expect(await applyNotebookOp(ritaClient, notebookUpdate(entryId, { body: 'The gyro trick fixed our turns.' }))).toBe('done');
	});

	test('a cross-team write changes nothing, and the op does not invent a failure for it', async () => {
		// WHAT 0026 DID TO THIS TEST, said plainly rather than papered over.
		// Before it, theo could READ this row and not WRITE it, which is the
		// exact shape judgeWrite's REFUSED branch exists for: zero rows, no
		// error, row still visible, so SHOW the refusal. After it, no caller
		// on the team is in that position any more, because reading and
		// writing the notebook are now the same permission.
		//
		// What is left is the TEAM boundary, and it is a different shape: RLS
		// filters zia's update to zero rows AND hides the row from her probe,
		// so the op reports done. That is correct rather than a swallowed
		// error: there is no row at this id for this caller, so there is
		// nothing to show her. It is also unreachable from the app, where an
		// op only ever names a row the queue's own owner loaded.
		const res = await applyNotebookOp(ziaClient, notebookUpdate(entryId, { body: 'overwritten' }));
		expect(res).toBe('done');

		// The positive control is the one that matters here: nothing moved.
		const { data } = await service.from('notebook_entries').select('body').eq('id', entryId);
		expect(data).toEqual([{ body: 'The gyro trick fixed our turns.' }]);
	});

	test('a replayed delete is done both times, and an edit whose target is gone is done, not an error', async () => {
		expect(await applyNotebookOp(ritaClient, notebookDelete(entryId))).toBe('done');
		// The second attempt is the replay a lost answer causes. The RPC refuses
		// it ("already in the bin"), and the op still reports done, because the
		// read policy no longer shows the row and that is what "did my delete
		// land" actually means.
		expect(await applyNotebookOp(ritaClient, notebookDelete(entryId))).toBe('done');

		// A SOFT DELETE (0020): gone from the author's reads...
		const { data: hers } = await ritaClient.from('notebook_entries').select('id').eq('id', entryId);
		expect(hers).toHaveLength(0);
		// ...and still on the table, stamped, which is what makes the undo and
		// the mentor's bin possible. The service role is the positive control:
		// without it, a soft delete and a hard one read identically from here.
		const { data } = await service.from('notebook_entries').select('id, deleted_at').eq('id', entryId);
		expect(data).toHaveLength(1);
		expect((data as unknown as { deleted_at: string | null }[])[0].deleted_at).not.toBeNull();

		expect(await applyNotebookOp(ritaClient, notebookUpdate(entryId, { body: 'ghost' }))).toBe('done');

		// And the restore that the ten-second undo calls brings it back.
		expect(await applyNotebookOp(ritaClient, notebookRestore(entryId))).toBe('done');
		const { data: back } = await ritaClient.from('notebook_entries').select('id').eq('id', entryId);
		expect(back).toHaveLength(1);
	});
});

describe('replayed recap edits', () => {
	test('the summary is last-write-wins and idempotent on the server-generated row', async () => {
		const op = recapUpdate(recapId, { summary: 'We planned the season kickoff.' });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const { data } = await service.from('meeting_recaps').select('summary').eq('id', recapId);
		expect(data).toEqual([{ summary: 'We planned the season kickoff.' }]);
	});

	test('a replayed confirm stamps once and stays stamped', async () => {
		const op = recapUpdate(recapId, { confirmed: true });
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');

		const first = await service
			.from('meeting_recaps')
			.select('confirmed_at, confirmed_by_student_id')
			.eq('id', recapId)
			.single();
		expect(first.data?.confirmed_at).not.toBeNull();
		expect(first.data?.confirmed_by_student_id).toBe(rita.studentId);

		// The replay: still confirmed, and the ORIGINAL stamp stands.
		expect(await applyNotebookOp(ritaClient, op)).toBe('done');
		const second = await service
			.from('meeting_recaps')
			.select('confirmed_at, confirmed_by_student_id')
			.eq('id', recapId)
			.single();
		expect(second.data?.confirmed_at).toBe(first.data?.confirmed_at);
		expect(second.data?.confirmed_by_student_id).toBe(rita.studentId);
	});

	test('a teammate with no role writes the summary, and CONFIRMING is refused with a sentence', async () => {
		const wrote = await applyNotebookOp(theoClient, recapUpdate(recapId, { summary: 'Theo added a line.' }));
		expect(wrote).toBe('done');

		// The one narrow act. The trigger raises, so this comes back as a real
		// error whose message the op passes through untouched: a sentence a
		// nine year old can act on, never a SQLSTATE.
		const refused = await applyNotebookOp(theoClient, recapUpdate(recapId, { confirmed: false }));
		expect(typeof refused === 'object' && refused !== null && 'message' in refused).toBe(true);
		expect((refused as { message: string }).message).toMatch(/Notebook and Values Lead or a mentor/i);
		expect((refused as { message: string }).message).not.toMatch(/meeting_recaps|42501|P0001/i);

		// Positive controls on both halves: his words landed, and the recap is
		// still confirmed because his attempt to reopen it did not.
		const { data } = await service
			.from('meeting_recaps')
			.select('summary, confirmed')
			.eq('id', recapId);
		expect(data).toEqual([{ summary: 'Theo added a line.', confirmed: true }]);
	});

	test('a rival on another team writes nothing into this recap', async () => {
		// Same shape as the cross-team entry write above: filtered to zero
		// rows and invisible to the probe, so the op reports done and the row
		// is untouched. The service role is what tells those two apart.
		const res = await applyNotebookOp(ziaClient, recapUpdate(recapId, { summary: 'not my session' }));
		expect(res).toBe('done');

		const { data } = await service.from('meeting_recaps').select('summary').eq('id', recapId);
		expect(data).toEqual([{ summary: 'Theo added a line.' }]);
	});
});
