/**
 * NOTEBOOK WRITE OPS: how one queued notebook edit becomes one PostgREST
 * call, and how the answer is judged. The WriteQueue delegates every notebook
 * op here, exactly as it delegates planner ops to $lib/planner/ops, and the
 * offline-replay test drives this function directly against the real stack.
 *
 * A notebook entry is a child's own words, written in a room whose wifi
 * drops: it goes to IndexedDB before the wire, replays with a client-minted
 * id so a retry collides instead of duplicating, and honors the repo's
 * zero-rows rule -- an UPDATE that RLS filtered comes back 204 with no error,
 * so every update asks for its rows back and probes when it gets none: still
 * visible means refused (SHOW it), gone means already done.
 */
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database, TablesInsert, TablesUpdate } from '$lib/supabase/database.types';
import { classifyPostgrest, type ApplyResult } from '$lib/student/postgrest';

type Client = SupabaseClient<Database>;

export type NotebookOp =
	| { kind: 'notebook_insert'; row: Record<string, unknown> }
	| { kind: 'notebook_update'; id: string; patch: Record<string, unknown> }
	| { kind: 'notebook_delete'; id: string }
	/** The Notebook Lead's recap edits: the summary text, or the confirmed
	 * flag (confirmed_at and the confirmed_by columns are server-stamped). */
	| { kind: 'recap_update'; id: string; patch: { summary?: string; confirmed?: boolean } };

const NOTEBOOK_KINDS = new Set(['notebook_insert', 'notebook_update', 'notebook_delete', 'recap_update']);

export function isNotebookOp(op: { kind: string }): op is NotebookOp {
	return NOTEBOOK_KINDS.has(op.kind);
}

/** Typed builders so call sites keep the generated row types. */
export function notebookInsert(row: TablesInsert<'notebook_entries'>): NotebookOp {
	return { kind: 'notebook_insert', row: row as Record<string, unknown> };
}
export function notebookUpdate(id: string, patch: TablesUpdate<'notebook_entries'>): NotebookOp {
	return { kind: 'notebook_update', id, patch: patch as Record<string, unknown> };
}
export function notebookDelete(id: string): NotebookOp {
	return { kind: 'notebook_delete', id };
}
export function recapUpdate(id: string, patch: { summary?: string; confirmed?: boolean }): NotebookOp {
	return { kind: 'recap_update', id, patch };
}

const REFUSED = 'The server did not accept this change.';

type WriteBack = {
	error: { code?: string | null; message?: string } | null;
	data: { id: string }[] | null;
};

/**
 * Zero rows back from a write is ambiguous: the row may be gone (a replay, or
 * someone deleted it) or RLS may have filtered the write (a refusal that must
 * be SHOWN). Probing through the caller's own read policies tells the two
 * apart: still visible means refused.
 */
async function judgeWrite(
	sb: Client,
	table: 'notebook_entries' | 'meeting_recaps',
	id: string,
	res: WriteBack
): Promise<ApplyResult> {
	if (res.error) return classifyPostgrest(res.error);
	if ((res.data ?? []).length > 0) return 'done';
	const probe = await sb.from(table).select('id').eq('id', id).maybeSingle();
	if (probe.error) return classifyPostgrest(probe.error);
	return probe.data ? { message: REFUSED } : 'done';
}

/**
 * Applies one notebook op. 'done' when the server holds the edit (or provably
 * already held it), 'transient' when the request never reached the server,
 * and a message when the server refused.
 */
export async function applyNotebookOp(sb: Client, op: NotebookOp): Promise<ApplyResult> {
	try {
		if (op.kind === 'notebook_insert') {
			// A refused insert ERRORS (42501 / with-check violation); a replayed
			// insert is a duplicate key, which classifyPostgrest counts as done.
			const { error } = await sb.from('notebook_entries').insert(op.row as never);
			return classifyPostgrest(error);
		}

		if (op.kind === 'notebook_update') {
			const res = await sb
				.from('notebook_entries')
				.update(op.patch as never)
				.eq('id', op.id)
				.select('id');
			return judgeWrite(sb, 'notebook_entries', op.id, res);
		}

		if (op.kind === 'notebook_delete') {
			const res = await sb.from('notebook_entries').delete().eq('id', op.id).select('id');
			return judgeWrite(sb, 'notebook_entries', op.id, res);
		}

		// recap_update. A recap is generated by the server, never inserted by a
		// client, so a gone row means the meeting itself was deleted: nothing
		// left to annotate, and nothing to scare a child with.
		const res = await sb
			.from('meeting_recaps')
			.update(op.patch)
			.eq('id', op.id)
			.select('id');
		return judgeWrite(sb, 'meeting_recaps', op.id, res);
	} catch {
		// fetch threw: the request never reached the server.
		return 'transient';
	}
}
